version: 2
aliases:

- &post-hook
  name: Notify about build and docker image pushed
  command: |
    echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
    echo 'export BUILD_STATUS_API_KEY="$BUILD_STATUS_API_KEY"' >> $BASH_ENV
    /tools/build_notify.sh
jobs:
  validate:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    steps:
    - checkout
    - run:
        - name: Validate Schema
        - command: xmllint --noout --schema xsd/NeTEx_publication.xsd examples/functions/stopPlace/Netex_01_StopPoints_NoFrills_1.xml
    - run: *post-hook
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - validate:
        context: org-carbon