version: 2
aliases:

jobs:
  build:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    steps:
    - checkout
    - run: echo "Running xmllint to validate schema"
    - run: xmllint --noout --schema xsd/NeTEx_publication.xsd examples/functions/stopPlace/Netex_01_StopPoints_NoFrills_1.xml
    - run: echo "Finished running xmllint"
workflows:
  version: 2
  install-validate:
    jobs:
    - validate:
        context: org-carbon