version: 2
aliases:

jobs:
  build:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    steps:
    - checkout
    - run: echo "Running xmllint to validate schema"
    - run: xmllint --noout --schema xsd/NeTEx_publication.xsd examples/functions/stopPlace/Netex_01_StopPoints_NoFrills_1.xml
    - run: echo "Finished running xmllint"
  trigger-dependants:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    steps:
      - checkout
      - run:
          name: Trigger dependant builds
          command: |
            echo 'export CIRCLE_API_TOKEN="$CIRCLE_API_TOKEN"' >> $BASH_ENV
            /tools/downstream_single_trigger.sh "github/entur/netex-java-model" "master"
workflows:
  version: 2
  install-validate:
    jobs:
    - build:
        context: org-carbon
    - trigger-dependants:
        context: org-carbon
        requires:
          - build
        filters:
          branches:
            only:
            - master
