# This Circle CI trigger example uses Entur open source projects
#   https://github.com/entur/netex-java-model
#   https://github.com/entur/circleci-toolbox-image (https://github.com/entur/circleci-toolbox-image/blob/master/tools/trigger_build.sh)
version: 1
aliases:
- &post_build
  name: Trigger downstream builds
  command: |
    echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
    echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    echo 'export GITHUB_TOKEN="$GITHUB_TOKEN"' >> $BASH_ENV
    /tools/trigger_build.sh "entur/netex-java-model.git" "master" "$(git log -1 --pretty=%B)"
jobs:
  build:
    docker:
    - image: host-URI/circleci-toolbox-image
      auth:
        username: _json_key
        password: $KEY
    steps:
    - checkout
    - run: echo "Running xmllint to validate schema"
    - run: xmllint --noout --schema xsd/NeTEx_publication.xsd examples/functions/stopPlace/Netex_01_StopPoints_NoFrills_1.xml
    - run: echo "Finished running xmllint"
  trigger-dependants:
    docker:
      - image: host-URI/circleci-toolbox-image
        auth:
          username: _json_key
          password: $KEY
    steps:
      - run: *post_build
workflows:
  version: 1
  install-validate:
    jobs:
    - build:
        context: org-host
    - trigger-dependants:
        context: org-host
        requires:
          - build
        filters:
          branches:
            only:
            - master
