version: 2
aliases:

jobs:
  validate:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    steps:
    - checkout
    - run:
        - name: Validate Schema
        - command: xmllint --noout --schema xsd/NeTEx_publication.xsd examples/functions/stopPlace/Netex_01_StopPoints_NoFrills_1.xml
workflows:
  version: 2
  validate:
    jobs:
    - validate:
        context: org-carbon