name: CI

on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event for branch ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install xmllint and xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils xsltproc

      - name: Validate structure and lint XSD and XML files
        run: ./.github/scripts/validate-and-lint.sh

      - name: Validate NeTEx XML examples
        run: ./.github/scripts/validate-examples.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9 # https://github.com/marketplace/actions/add-commit
        with:
          default_author: github_actions
          message: 'Lint and update documentation tables'
