2c2
< <xsd:schema xmlns="http://www.netex.org.uk/netex" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:siri="http://www.siri.org.uk/siri" targetNamespace="http://www.netex.org.uk/netex" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.2.2" id="netex_resourceFrame_version">
---
> <xsd:schema xmlns="http://www.netex.org.uk/netex" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:siri="http://www.siri.org.uk/siri" targetNamespace="http://www.netex.org.uk/netex" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0" id="netex_resourceFrame_version">
13c13
< 				<Creator>First Drafted for version 1.0 CEN TC278 WG3 SG6 Editor Nicholas Knowles.  mailto:schemer@netex.org.uk</Creator>
---
> 				<Creator>First Drafted for version 1.0 CEN TC278 WG3 SG6 Editor Nicholas Knowles.</Creator>
20c20
< 				<Date><Modified>2017-03-28</Modified>CR031 Add Zones to RESOURCE FRAME 
---
> 				<Date><Modified>2017-03-28</Modified>CR031 Add Zones to RESOURCE FRAME
27a28,31
> 				<Date><Modified>2023-02-02</Modified>Add DECK PLAN CHANGES.
> 				</Date>
> 				<Date><Modified>2023-11-06</Modified>Add contracts to RESOURCE FRAME.
> 				</Date>
87c91
< 					<xsd:attribute name="id" type="ResourceFrameIdType"/>
---
> 					<xsd:attribute name="id" type="ResourceFrameIdType" use="required"/>
114a119,120
> 			<xsd:group ref="VehicleTypeProfileInFrameGroup"/>
> 			<xsd:group ref="TrainElementTypesInFrameGroup"/>
115a122
> 			<xsd:group ref="DeckPlanInFrameGroup"/>
118a126
> 			<xsd:group ref="BookingArrangementInFrameGroup"/>
133c141
< 					<xsd:documentation>RESPONSIBILITY Roles used in frame.</xsd:documentation>
---
> 					<xsd:documentation>RESPONSIBILITY roles used in frame. +v2.0</xsd:documentation>
140a149,153
> 			<xsd:element name="contracts" type="contractsInFrame_RelStructure" minOccurs="0">
> 				<xsd:annotation>
> 					<xsd:documentation>CONTRACTs used in frame. +v2.0</xsd:documentation>
> 				</xsd:annotation>
> 			</xsd:element>
145c158
< 			<xsd:documentation>General  Elements of a RESOURCE FRAME.</xsd:documentation>
---
> 			<xsd:documentation>General Elements of a RESOURCE FRAME.</xsd:documentation>
